django_json/account/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth.views import LoginView, LogoutView, logout_then_login, PasswordChangeView, \
    PasswordChangeDoneView, PasswordResetView, PasswordResetConfirmView, PasswordResetDoneView, \
    PasswordResetCompleteView


app_name = 'account'

urlpatterns = [
    path('login/', LoginView.as_view(template_name='account/login.html', redirect_field_name='index'), name='login'),
    path('logout/', LogoutView.as_view(template_name='account/logout.html'), name='logout'),
    path('logout_then_login', logout_then_login, name='logout_then_login'),
]

django_json/django_json/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainapp.urls')),
    path('account/', include('account.urls')),
]

django_json/mainapp/urls.py
from django.urls import path
from .views import HomeView, ChartImportExportData, ImpExpView, IndustryView, ChartIndustryData

app_name = 'mainapp'

urlpatterns = [
    path('', HomeView.as_view(), name='index'),
    path('import-export/', ImpExpView.as_view(), name='import-export'),
    path('industry/', IndustryView.as_view(), name='industry'),
    path('api/chart/data/', ChartImportExportData.as_view()),
    path('api/chart/data/industry/', ChartIndustryData.as_view()),
]

django_json/account/models.py
from django.db import models

# Create your models here.

django_json/mainapp/models.py
from django.db import models


# Create your models here.

class Dictionary(models.Model):
    class Meta:
        verbose_name = 'Словаь'
        ordering = ('ids', )
    ids = models.FloatField('id', unique=True)
    dim_name = models.CharField('Название категории', max_length=256)
    ident = models.SlugField('Индекфикационный номер', unique=True)
    is_ind = models.FloatField('Активно', default=0.0)

    def __str__(self):
        return f'{self.dim_name} - {self.ident}'


class Product(models.Model):
    class Meta:
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'
        ordering = ('ids', 'n_order')

    ids = models.FloatField('id', unique=True)
    parent_id = models.FloatField()
    name = models.CharField('Название', max_length=512)
    n_order = models.FloatField()
    methodology = models.CharField('Методология', max_length=256, blank=True)
    ei = models.CharField(blank=True, max_length=128)

    def __str__(self):
        return f'{self.name}'


class Order(models.Model):
    class Meta:
        verbose_name = 'Заказ'
        verbose_name_plural = 'Заказы'

    r_n_u_m = models.FloatField('Номер строки данных')
    indicators = models.FloatField('Показатели - DIM_2954')
    view_type = models.FloatField('Вид представления "DIM_369"')
    is_calc = models.FloatField('Возможность посчитать?')
    country = models.FloatField('Страна')
    direction_of_travel = models.FloatField('Направление перемещений - DIM_2955')
    goods_apk = models.FloatField(blank=True, null=True)
    goods_industrial = models.FloatField(blank=True, null=True)
    type_of_goods_industrial = models.FloatField(blank=True, null=True)
    type_of_goods_apk = models.ForeignKey(Product, related_name='product_apk', null=True,
                                          on_delete=models.SET_NULL)
    ddate = models.FloatField(null=True, blank=True)
    # dt = models.DateTimeField()
    dl = models.FloatField()
    id_ind = models.FloatField(null=True, blank=True)
    vl = models.FloatField('Значение в долларах США')

    def __str__(self):
        return f'Заказ - {self.id}'

django_json/account/views.py
from django.shortcuts import render

# Create your views here.

django_json/mainapp/views.py
from django.shortcuts import render
from django.views.generic import View

from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework.authentication import SessionAuthentication, BasicAuthentication
from rest_framework.permissions import IsAuthenticated

from .models import Order, Product


# Create your views here.

class HomeView(View):
    def get(self, request, *args, **kwargs):
        return render(request, 'mainapp/index.html', {})


class ImpExpView(View):
    def get(self, request, *args, **kwargs):
        return render(request, 'mainapp/import-export.html', {})


class IndustryView(View):
    def get(self, request, *args, **kwargs):
        return render(request, 'mainapp/industry.html', {})


class ChartImportExportData(APIView):
    """
    View to list all users in the system.
    * Requires token authentication.
    * Only admin users are able to access this view.
    """
    authentication_classes = [SessionAuthentication, BasicAuthentication]
    permission_classes = [IsAuthenticated]

    def get(self, request, format=None):
        """
        Return a list of all users.
        """
        orders_import = Order.objects.filter(direction_of_travel__exact=2.0,
                                             type_of_goods_apk__parent_id__exact=1.0).count()
        orders_export = Order.objects.filter(direction_of_travel__exact=3.0,
                                             type_of_goods_apk__parent_id__exact=1.0).count()
        labels = ['import', 'export']
        default_items = [orders_import, orders_export]
        data = {
            'labels': labels,
            'default': default_items
        }
        return Response(data)


class ChartIndustryData(APIView):
    """
    View to list all users in the system.
    * Requires token authentication.
    * Only admin users are able to access this view.
    """
    authentication_classes = [SessionAuthentication, BasicAuthentication]
    permission_classes = [IsAuthenticated]

    def get(self, request, format=None):
        """
        Return a list of all users.
        """
        labels = [label.name for label in Product.objects.filter(parent_id='1.0')]

        industry_count = []

        ind_id = [label.id for label in Product.objects.filter(parent_id='1.0')]
        for i in ind_id:
            num = Product.objects.filter(parent_id=i).count()
            industry_count.append(num)

        data = {
            'labels': labels,
            'default': industry_count
        }
        return Response(data)

django_json/mainapp/templates/mainapp/import-export.html
{% extends 'base.html' %}
{% load static %}

<script>
    {% block jquery %}
        var endpoint = '/api/chart/data/';
        var defaultData = [];
        var labels = [];
        $.ajax({
            method: "GET",
            url: endpoint,
            success: function (data) {
                labels = data.labels
                defaultData = data.default
                console.log(data)
                setChart()
            },
            error: function (data_error) {
                console.log('error')
                console.log(data_error)
            }
        })
        function setChart() {
            var ctx = document.getElementById('myChart').getContext('2d');
            var myChart = new Chart(ctx, {
                type: 'pie',
                data: {
                    labels: labels,
                    datasets: [{
                        label: '# Import/export',
                        data: defaultData,
                        backgroundColor: [
                            'rgba(255, 99, 132, 0.2)',
                            'rgba(54, 162, 235, 0.2)',
                            'rgba(255, 206, 86, 0.2)',
                            'rgba(75, 192, 192, 0.2)',
                            'rgba(153, 102, 255, 0.2)',
                            'rgba(255, 159, 64, 0.2)'
                        ],
                        borderColor: [
                            'rgba(255, 99, 132, 1)',
                            'rgba(54, 162, 235, 1)',
                            'rgba(255, 206, 86, 1)',
                            'rgba(75, 192, 192, 1)',
                            'rgba(153, 102, 255, 1)',
                            'rgba(255, 159, 64, 1)'
                        ],
                        borderWidth: 1
                    }]
                },
                options: {
                    scales: {
                        yAxes: [{
                            ticks: {
                                beginAtZero: true
                            }
                        }]
                    }
                }
            })
        }
    {% endblock %}
</script>

{% block content %}
    <div class="row">
        <div class="col-12">
            <div class="col-6">
                <h3>Один из графиков(схем) должен содержать информацию об объемах импорта("DIM_2955": 2.0) и
                    экспорта("DIM_2955": 3.0) Отраслей("parent_id": 1.0) АПК;</h3>
                <canvas id="myChart"></canvas>
            </div>
        </div>
    </div>
{% endblock %}

django_json/mainapp/templates/mainapp/index.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
    <div class="row">
        <div class="col-12">
            <div class="col-6">
                <h1>Hello, {{ user.username }}!
                </h1>

            </div>
        </div>
    </div>
{% endblock %}

django_json/mainapp/templates/mainapp/industry.html
{% extends 'base.html' %}
{% load static %}

<script>
    {% block jquery %}
        var endpoint = '/api/chart/data/industry/';
        var defaultData = [];
        var labels = [];
        $.ajax({
            method: "GET",
            url: endpoint,
            success: function (data) {
                labels = data.labels
                defaultData = data.default
                console.log(data)
                setChart()
            },
            error: function (data_error) {
                console.log('error')
                console.log(data_error)
            }
        })
        function setChart() {
            var ctx = document.getElementById('myChart').getContext('2d');
            var myChart = new Chart(ctx, {
                type: 'pie',
                data: {
                    labels: labels,
                    datasets: [{
                        label: '',
                        data: defaultData,
                        backgroundColor: [
                            'rgba(255, 99, 132, 0.2)',
                            'rgba(54, 162, 235, 0.2)',
                            'rgba(255, 206, 86, 0.2)',
                            'rgba(75, 192, 192, 0.2)',
                            'rgba(153, 102, 255, 0.2)',
                            'rgba(255, 159, 64, 0.2)'
                        ],
                        borderColor: [
                            'rgba(255, 99, 132, 1)',
                            'rgba(54, 162, 235, 1)',
                            'rgba(255, 206, 86, 1)',
                            'rgba(75, 192, 192, 1)',
                            'rgba(153, 102, 255, 1)',
                            'rgba(255, 159, 64, 1)'
                        ],
                        borderWidth: 1
                    }]
                },
                options: {
                    scales: {
                        yAxes: [{
                            ticks: {
                                beginAtZero: true
                            }
                        }]
                    }
                }
            })
        }
    {% endblock %}
</script>

{% block content %}
    <div class="row">
        <div class="col-12">
            <div class="col-6">
                <h3>Предоставлена детализированная информация по Отраслям (например: круговая диаграмма с информацией о
                    подотраслях с переключателем Отрасли);</h3>
                <canvas id="myChart"></canvas>
            </div>
        </div>
    </div>
{% endblock %}

django_json/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Main</title>
    {% block css %}
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
              integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk"
              crossorigin="anonymous">
    {% endblock %}
</head>
<body>
<div class="container">
    {% include 'snippets/menu_snippet.html' %}
    {% block content %}
    {% endblock %}
</div>
{% block js %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
            integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
            integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.3/Chart.js">
    </script>
    <script>
    $(document).ready(function () {
        {% block jquery %}
        {% endblock %}
    });
    </script>
{% endblock %}
</body>
</html>

django_json/templates/snippets/menu_snippet.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'mainapp:index' %}">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'mainapp:import-export' %}">Import/export</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'mainapp:industry' %}">Industry</a>
      </li><li class="nav-item">
        <a class="nav-link" href="{% url 'account:login' %}">Login</a>
      </li><li class="nav-item">
        <a class="nav-link" href="{% url 'account:logout' %}">Logout</a>
      </li>
    </ul>
  </div>
</nav>